---
- name: install nginx web server
  apt:
    name: nginx
    state: present
    update_cache: true

- name: start nginx
  service:
    name: nginx
    state: started

- name: ensure nginx proxy conf is present
  template:
    src: proxy.conf.j2
    dest: "/etc/nginx/proxy.conf"
    owner: root
    group: root
    mode: 0644

- name: ensure nginx conf is present
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  register: nginxconf

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: nginxconf.changed