---
- name: ensure certbot is present
  apt:
    name: certbot
    state: present
    update_cache: true

- name: ensure certbot nginx plugin is present
  apt:
    name: python3-certbot-nginx
    state: present
    update_cache: true

- name: execute certbot command
  become: yes
  command: "certbot certonly --nginx -d {{ domain }} -m {{ letsencrypt_email }} --agree-tos -n"
  args:
    creates: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"


