---
- name: install nginx web server
  apt:
    name: nginx
    state: present
    update_cache: true
  notify: start nginx

- name: ensure nginx proxy conf is present
  template:
    src: proxy.conf.j2
    dest: "/etc/nginx/proxy.conf"
    owner: root
    group: root
    mode: 0644

- name: ensure nginx conf is present
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: install site config
  template:
    src: site.conf.j2
    dest: "/etc/nginx/sites-available/{{domain}}.conf"
    owner: root
    group: root
    mode: 0644

- name: remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: enable site config
  file:
    src: "/etc/nginx/sites-available/{{domain}}.conf"
    dest: "/etc/nginx/sites-enabled/{{domain}}"
    owner: root
    group: root
    state: link
  notify: restart nginx

