---
- name: ensure app folder is present
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: copy api binary to server
  copy:
    src: "{{ src_dir }}/build/floridaman"
    dest: "{{ app_dir }}/floridaman"
    owner: ubuntu
    group: ubuntu
    mode: '0744'

- name: create service file
  template:
    src: floridaman.service.j2
    dest: /lib/systemd/system/floridaman.service
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: floridaman api is restarted
  service:
    name: floridaman
    state: started
    enabled: yes