---
- name: ensure app folder is present
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: copy api binary to server
  copy:
    src: "{{ src_dir }}/build/floridaman_linux"
    dest: "{{ app_dir }}/floridaman"
    owner: ubuntu
    group: ubuntu
    mode: '0744'

- name: create service file
  template:
    src: floridaman.service.j2
    dest: /lib/systemd/system/floridaman.service
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: create readreddit timer file
  template:
    src: floridaman-readreddit.timer.j2
    dest: /lib/systemd/system/floridaman-readreddit.timer
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: create readreddit cron service file
  template:
    src: floridaman-readreddit.service.j2
    dest: /lib/systemd/system/floridaman-readreddit.service
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: floridaman api is restarted
  service:
    name: floridaman
    state: started
    enabled: yes

- name: floridaman readreddit service is enabled
  service:
    name: floridaman-readreddit.service
    enabled: yes

- name: floridaman readreddit timer is enabled and started
  service:
    name: floridaman-readreddit.timer
    state: started
    enabled: yes