name: 'Floridaman CI'

on: [push, pull_request]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.2

      - name: test
        run: |
          make test